### PR TITLE
add pcap_std_dev option in target.ini for top_defines entry

### LINKED ISSUE #63: Add configuration framework for top_defines entry for std_dev
Required for #62

### PR DESCRIPTION
**Pull request by shu-soleil**
Fixes #63

### CODE REVIEW

**Comment by shu-soleil** [comment]
Since no change is related to the 'make boot', could we merge to the master ? The merge should launch another check ?

By te way the check of PR #66 was also throttled at 'make boot' step, and it has been merged. But it seems only the 'make_docs' was checked after the merge.  
```All checks have passed
1 successful check
@github-actions
Docs CI / make_docs (push)
Details```

**Comment by Araneidae** [comment]
Looking at this more closely, in particular looking for examples of the presence or absence of the `pcap_std_dev` flag in the tests, I wonder: is `PandABox.target.ini` the correct place for this option?

Have to say, I was expecting to see this option against the individual build or "app" configurations.  After all, the idea of making this optional is not so much global target option, so much as to ensure that if a build configuration needs to trade off more blocks for less capture functionality it should have the option.

So, shouldn't this option be part of the `apps/*.app.ini` file configuration?  In particular, I'd expect to see a test that builds with, and one without this new option.

**Comment by shu-soleil** [comment]
We made the changes according to the requirements mentioned in https://github.com/PandABlocks/PandABlocks-FPGA/commit/e07651672da7fd38f045ac98c37f4f54eda8b3bc#commitcomment-57987906 and https://github.com/PandABlocks/PandABlocks-FPGA/commit/e07651672da7fd38f045ac98c37f4f54eda8b3bc#commitcomment-57988055. 

I can understand this solution since the option relates to the target resource limitation. But if you think it better to move the option to app.ini file, it might be done in a new issue or PR ? Otherwise all the changes made here don't make sense and are not coherent with the PR title.

**Comment by Araneidae** [comment]
@shu-soleil, I completely understand your frustration!  I know that this tiny little fix is turning into a great big meal.  Still, it would be nice to do it right

Think I'd like some input from @tomtrafford and @thomascobb here.

**Comment by thomascobb** [comment]
Personally, I'm fine with leaving it at the target level. If we need to disable it on a build-by-build basis we could add a `disable-options` entry to each app.

**Comment by thomascobb** [comment]
I'm hoping we can enable it for every PandABox target build, and disable it for the Zedboard build

**Comment by tomtrafford** [comment]
I think it made sense in the target.ini as it was based on the target's capabilities. It would be a fairly simple modification to either move this to the app.ini or add a new flag in the app.ini to enable/disable the options. 

I have started looking into why the CI sometimes times out and it is unrelated to these changes. You can try rerunning the job to confirm it will pass, or once everyone is happy with the changes, merge without all the jobs passing.

**Comment by Araneidae** [comment]
But this is not really a function of the target's capabilities, all of our targets are fully capable of implementing this functionality.  It's more going to be a matter of application complexity, which is why I was imagining this to be an application option.

**Comment by thomascobb** [comment]
Technically that is true, but the autogeneration packages PCAP at the target level as it has hooks into everything, so the option fits better there unless we revisit that decision too

**Comment by thomascobb** [comment]
https://github.com/PandABlocks/PandABlocks-FPGA/blob/07644adb0c8250e0fd8a7174545cf5507bcad7a7/targets/PandABox/PandABox.target.ini#L26-L27

**Comment by shu-soleil** [comment]
It seems the check get throttled again, and new errors appeared during 'make zpkg' while it passed on my local PC:
```src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f26a15125c0 
Abnormal program termination (11)
Please check '/home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/build/apps/PandABox-fmc_24vio/FPGA/hs_err_pid8831.log' for details
segfault in /scratch/Xilinx/Vivado/2020.2/bin/unwrapped/lnx64.o/vivado -exec vivado -mode batch -source /home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/PandABlocks-fpga/common/scripts/build_top.tcl -log /home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/build/apps/PandABox-fmc_24vio/FPGA/build_top.log -nojournal -tclargs /home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/PandABlocks-fpga -tclargs /home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/PandABlocks-fpga/targets/PandABox -tclargs /home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/build/apps/PandABox-fmc_24vio/FPGA -tclargs /home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/build/apps/PandABox-fmc_24vio/autogen -tclargs /home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/build/targets/PandABox/ip_repo -tclargs /home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/build/targets/PandABox/panda_ps/panda_ps.srcs/sources_1/bd/panda_ps/panda_ps.bd -tclargs batch, exiting...
make[1]: *** [/home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/PandABlocks-fpga/common/fpga.make:147: /home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/build/apps/PandABox-fmc_24vio/FPGA/panda_top.bit] Error 139
make[1]: Leaving directory '/home/runner/work/PandABlocks-FPGA/PandABlocks-FPGA/build/apps/PandABox-fmc_24vio/FPGA'
make: *** [Makefile:230: fpga-bit] Error 2
Error: Process completed with exit code 2.
```
Could I merge the changes to the master if you are OK ? We'd like to pull the changes to pcap_std_dev branch and push it here then. Thierry will finish his current contract this week... 

The discussion of where to put the option could be a new issue if required ?

**Pull request merged**
