### PR TITLE
Merge master into StdDev branch for review

### PR DESCRIPTION
**Pull request by Araneidae**
As requested in https://github.com/PandABlocks/PandABlocks-server/issues/13

### CODE REVIEW

**Comment by thomascobb** [comment]
@shu-soleil please could someone resolve these merge conflicts so we can build this and compare FPGA utilization?

**Comment by shu-soleil** [comment]
Yes I've made the merge on my local repo and am trying the build.

**Comment by shu-soleil** [comment]
@thomascobb The merge has been done, the build has passed for PandABox-no-fmc and PandABox-sfp2_udpontrig app.

**Comment by thomascobb** [comment]
@tomtrafford please could you try building this especially for the ADC zpkg?

**Comment by tomtrafford** [comment]
@thomascobb I have been able to build some of the zpkgs however the ACQ430 zpkg build has failed with a "Timing constraints weren't met." error

**Comment by thomascobb** [comment]
@shu-soleil that's been my main concern with adding std-dev into this, that there isn't enough space in the FPGA. Would you mind building the ACQ430 zpkg locally and see if there's any pipelining you could add to the std-dev code to make it meet timing?

**Comment by shu-soleil** [comment]
@thomascobb I checked ACQ430 building locally which also failed due to the timing error, Thierry will be back to office next week, he will take a look into this issue.

**Comment by shu-soleil** [comment]
@thomascobb I pushed the changes suggested by Thierry, the build of both ACQ427 and ACQ430 passed. Could you have a look if the change will impact your application ?

**Pull request merged**
